/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 water.gltf
Author: UJWAL CHAUHAN (https://sketchfab.com/xamplle)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/water-waves-142c2596d1944cd0bf4fc1f490c4c248
Title: water waves
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useEffect } from "react";

export function Water() {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/water.gltf");
  const { actions } = useAnimations(animations, group);

  return (
    <group dispose={null} scale={[0.1, 0.1, 0.1]}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="41988359a78d4916a5719b50015c7b57abccleanermaterialmergergles">
            <group name="Object_2" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Object_3">
                <group name="Object_4">
                  <group name="MorphMainGroup">
                    <mesh
                      name="Plane__CopyShape"
                      geometry={nodes.Plane__CopyShape.geometry}
                      material={materials.Plane__CopyShape}
                      morphTargetDictionary={
                        nodes.Plane__CopyShape.morphTargetDictionary
                      }
                      morphTargetInfluences={
                        nodes.Plane__CopyShape.morphTargetInfluences
                      }
                    />
                  </group>
                  <group name="MorphMainGroup_1">
                    <mesh
                      name="Plane__CopyShape_1"
                      geometry={nodes.Plane__CopyShape_1.geometry}
                      material={materials.Plane__CopyShape}
                      morphTargetDictionary={
                        nodes.Plane__CopyShape_1.morphTargetDictionary
                      }
                      morphTargetInfluences={
                        nodes.Plane__CopyShape_1.morphTargetInfluences
                      }
                    />
                  </group>
                </group>
                <group name="Object_9">
                  <group name="MorphMainGroup_2">
                    <mesh
                      name="Plane__CopyShape_2"
                      geometry={nodes.Plane__CopyShape_2.geometry}
                      material={materials.Plane__CopyShape}
                      morphTargetDictionary={
                        nodes.Plane__CopyShape_2.morphTargetDictionary
                      }
                      morphTargetInfluences={
                        nodes.Plane__CopyShape_2.morphTargetInfluences
                      }
                    />
                  </group>
                  <group name="MorphMainGroup_3">
                    <mesh
                      name="Plane__CopyShape_3"
                      geometry={nodes.Plane__CopyShape_3.geometry}
                      material={materials.Plane__CopyShape}
                      morphTargetDictionary={
                        nodes.Plane__CopyShape_3.morphTargetDictionary
                      }
                      morphTargetInfluences={
                        nodes.Plane__CopyShape_3.morphTargetInfluences
                      }
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/water.gltf");
